# Generated by Django 5.1 on 2024-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('altura', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
